# Generated by Django 5.2.8 on 2025-12-10 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales', 'Sales'), ('project_manager', 'Project Manager')], default='sales', max_length=20)),
                ('can_access_invoice_generation', models.BooleanField(default=False, verbose_name='Invoice Generation')),
                ('can_access_inquiry_handler', models.BooleanField(default=False, verbose_name='Inquiry Handler')),
                ('can_access_quotation_generation', models.BooleanField(default=False, verbose_name='Quotation Generation')),
                ('can_access_additional_supply', models.BooleanField(default=False, verbose_name='Additional Supply')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
