# Generated by Django 6.0 on 2026-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiryhandler',
            options={'ordering': ['-year_month_order', '-serial_number'], 'verbose_name': 'Inquiry Handler', 'verbose_name_plural': 'Inquiry Handlers'},
        ),
        migrations.AddField(
            model_name='inquiryhandler',
            name='serial_number',
            field=models.IntegerField(default=0, help_text='Serial number extracted from create_id for ordering within month'),
        ),
        migrations.AddField(
            model_name='inquiryhandler',
            name='year_month_order',
            field=models.CharField(blank=True, help_text='Computed field for month-wise ordering (YYYY-MM format)', max_length=10),
        ),
    ]
