# Generated by Django 5.2.8 on 2025-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_userprofile_role_userprofile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('plant', models.CharField(choices=[('surat', 'Surat'), ('goa', 'Goa'), ('pune', 'Pune')], max_length=20, verbose_name='Plant Location')),
                ('address', models.TextField(verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
