# Generated by Django 5.2.8 on 2025-12-12 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='plant',
            field=models.CharField(choices=[('surat', 'Surat'), ('goa', 'Goa'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad')], max_length=20, verbose_name='Plant Location'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='PO Number')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order Value')),
                ('days_to_mfg', models.PositiveIntegerField(verbose_name='Days to Manufacturing')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('due_days', models.IntegerField(blank=True, help_text='Positive: days remaining, Negative: days overdue', null=True, verbose_name='Due Days')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='dashboard.contact', verbose_name='Client')),
                ('project_manager', models.ForeignKey(blank=True, limit_choices_to={'userprofile__roles__contains': 'project_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('sales_person', models.ForeignKey(blank=True, limit_choices_to={'userprofile__roles__contains': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Sales Person')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
