# Generated by Django 5.2.8 on 2025-12-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_contact_plant_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='project_manager_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage (e.g., 3.25 for 3.25%)', max_digits=5, null=True, verbose_name='Project Manager Percentage (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sales_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage (e.g., 5.50 for 5.5%)', max_digits=5, null=True, verbose_name='Sales Percentage (%)'),
        ),
    ]
