# Generated by Django 5.2.8 on 2025-12-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_purchaseorder_project_manager_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='plant',
            field=models.CharField(max_length=100, verbose_name='Plant Location'),
        ),
    ]
