# Generated by Django 5.2.8 on 2025-12-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_contact_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Enter invoice number manually', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(help_text='Enter invoice date manually', verbose_name='Invoice Date')),
                ('customer_name', models.CharField(help_text='Auto-fetched based on client selection', max_length=200, verbose_name='Customer Name')),
                ('order_value', models.DecimalField(decimal_places=2, help_text='Auto-fetched from selected purchase order', max_digits=12, verbose_name='Order Value')),
                ('grn_date', models.DateField(help_text='Enter GRN date manually', verbose_name='GRN Date')),
                ('payment_due_date', models.DateField(help_text='Auto-calculated: GRN Date + 15 days', verbose_name='Payment Due Date')),
                ('due_days', models.IntegerField(help_text='Auto-calculated: days remaining (positive) or overdue (negative)', verbose_name='Due Days')),
                ('remarks', models.TextField(blank=True, help_text='Enter remarks manually (optional)', null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Select client from database', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='dashboard.contact', verbose_name='Client')),
                ('purchase_order', models.ForeignKey(help_text='Select purchase order to auto-fetch value', on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
