# Generated by Django 5.2.8 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Auto-fetched based on client selection', max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_days',
            field=models.IntegerField(blank=True, help_text='Auto-calculated: days remaining (positive) or overdue (negative)', null=True, verbose_name='Due Days'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-fetched from selected purchase order', max_digits=12, null=True, verbose_name='Order Value'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Auto-calculated: GRN Date + 15 days', null=True, verbose_name='Payment Due Date'),
        ),
    ]
