# Generated by Django 5.2.8 on 2025-12-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_invoice_customer_name_alter_invoice_due_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='Auto-generated ID (e.g., KEC020JY2025)', max_length=15, unique=True, verbose_name='Create ID')),
                ('status', models.CharField(choices=[('Inputs', 'Inputs'), ('Pending', 'Pending'), ('Inspection', 'Inspection'), ('Enquiry', 'Enquiry'), ('Quotation', 'Quotation'), ('Negotiation', 'Negotiation'), ('Enquiry Hold', 'Enquiry Hold'), ('PO-Confirm', 'PO-Confirm'), ('Design Review', 'Design Review'), ('Manufacturing', 'Manufacturing'), ('Stage-Inspection', 'Stage-Inspection'), ('Dispatch', 'Dispatch'), ('GRN', 'GRN'), ('Project Closed', 'Project Closed'), ('Lost', 'Lost'), ('PO Hold', 'PO Hold'), ('Design', 'Design'), ('Material Receive', 'Material Receive'), ('Approval', 'Approval')], default='Inputs', help_text='Select current status', max_length=20, verbose_name='Status')),
                ('opportunity_id', models.CharField(blank=True, help_text='Auto-generated based on status (e.g., eKEC020JY2025)', max_length=20, verbose_name='Opportunity ID')),
                ('lead_description', models.TextField(help_text='Enter lead description manually', verbose_name='Lead Description')),
                ('customer_name', models.CharField(blank=True, help_text='Auto-fetched based on client selection', max_length=200, verbose_name='Customer Name')),
                ('quote_no', models.CharField(blank=True, help_text='Auto-generated quote number', max_length=15, verbose_name='Quote Number')),
                ('date_of_quote', models.DateField(help_text='Enter quote date manually', verbose_name='Date of Quote')),
                ('remarks', models.TextField(blank=True, help_text='Enter remarks manually (optional)', null=True, verbose_name='Remarks')),
                ('ba', models.CharField(help_text='Enter BA name manually', max_length=100, verbose_name='BA (Business Analyst)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Select client from database', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='dashboard.contact', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Inquiry Handler',
                'verbose_name_plural': 'Inquiry Handlers',
                'ordering': ['-created_at'],
            },
        ),
    ]
