# Generated by Django 5.2.8 on 2025-12-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_inquiryhandler'),
    ]

    operations = [
    ]
