# Generated by Django 5.2.8 on 2025-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20251216_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryhandler',
            name='remarks_add',
            field=models.TextField(blank=True, help_text='Enter additional supply remarks manually (optional)', null=True, verbose_name='Additional Supply Remarks'),
        ),
        migrations.AlterField(
            model_name='inquiryhandler',
            name='quote_no',
            field=models.CharField(blank=True, help_text='Same as Create ID (e.g., KEC020JY2025)', max_length=15, verbose_name='Quote Number'),
        ),
    ]
