# Generated by Django 5.2.8 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_inquiryhandler_remarks_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryhandler',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Inputs', 'Inputs'), ('Pending', 'Pending'), ('Inspection', 'Inspection'), ('Quotation', 'Quotation'), ('Negotiation', 'Negotiation'), ('Enquiry Hold', 'Enquiry Hold'), ('PO-Confirm', 'PO-Confirm'), ('Design Review', 'Design Review'), ('Manufacturing', 'Manufacturing'), ('Stage-Inspection', 'Stage-Inspection'), ('Dispatch', 'Dispatch'), ('GRN', 'GRN'), ('Project Closed', 'Project Closed'), ('Lost', 'Lost'), ('PO Hold', 'PO Hold'), ('Design', 'Design'), ('Material Receive', 'Material Receive'), ('Approval', 'Approval')], default='Inputs', help_text='Select current status', max_length=20, verbose_name='Status'),
        ),
    ]
