# Generated by Django 5.2.8 on 2025-12-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_inquiryhandler_status'),
    ]

    operations = [
        # Rename client field to company in Contact model
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='company',
        ),
        # Rename client field to company in PurchaseOrder model
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='client',
            new_name='company',
        ),
        # Rename client field to company in Invoice model
        migrations.RenameField(
            model_name='invoice',
            old_name='client',
            new_name='company',
        ),
        # Rename client field to company in InquiryHandler model
        migrations.RenameField(
            model_name='inquiryhandler',
            old_name='client',
            new_name='company',
        ),
    ]
