# Generated by Django 5.2.8 on 2025-12-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_client_to_company'),
    ]

    operations = [
        # Create Company model
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('city_1', models.CharField(max_length=100, verbose_name='Primary City')),
                ('city_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary City')),
                ('address_1', models.TextField(verbose_name='Primary Address')),
                ('address_2', models.TextField(blank=True, null=True, verbose_name='Secondary Address')),
                ('address_3', models.TextField(blank=True, null=True, verbose_name='Tertiary Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name', 'city_1'],
            },
        ),
        
        # Add unique constraint for company name per city
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_name', 'city_1')},
        ),
        
        # Add new fields to Contact model (nullable first)
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client/Contact Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Primary Email Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary Phone Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tertiary Phone Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location (City)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='individual_address',
            field=models.TextField(blank=True, null=True, verbose_name='Individual Address'),
        ),
        
        # Make existing fields nullable for backward compatibility
        migrations.AlterField(
            model_name='contact',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='plant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plant Location'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
