# Generated by Django 5.2.8 on 2025-12-18 07:27

from django.db import migrations, models
import django.db.models.deletion


def create_default_companies_and_migrate_data(apps, schema_editor):
    """Create companies from existing contact data and migrate relationships"""
    Contact = apps.get_model('dashboard', 'Contact')
    Company = apps.get_model('dashboard', 'Company')
    
    # Get all unique company names from existing contacts
    existing_companies = Contact.objects.values('company').distinct()
    
    company_mapping = {}
    
    for contact_company in existing_companies:
        company_name = contact_company['company']
        if company_name:
            # Create or get company (use first city as default)
            company, created = Company.objects.get_or_create(
                company_name=company_name,
                city_1='Default City',  # Will be updated later
                defaults={
                    'address_1': 'Default Address',  # Will be updated later
                }
            )
            company_mapping[company_name] = company
    
    # Migrate contact data
    for contact in Contact.objects.all():
        # Migrate basic fields
        if not contact.contact_name and contact.customer_name:
            contact.contact_name = contact.customer_name
        
        if not contact.email_1 and hasattr(contact, 'email') and contact.email:
            contact.email_1 = contact.email
        
        if not contact.phone_1:
            contact.phone_1 = '000-000-0000'  # Default phone
        
        if not contact.individual_address and contact.address:
            contact.individual_address = contact.address
        
        if not contact.location_city and contact.plant:
            contact.location_city = contact.plant
        
        contact.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration if needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_add_company_and_update_contact'),
    ]

    operations = [
        # Run data migration first
        migrations.RunPython(create_default_companies_and_migrate_data, reverse_migration),
        
        # Add the foreign key relationship (nullable first)
        migrations.AddField(
            model_name='contact',
            name='new_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Company'),
        ),
    ]
