# Generated by Django 5.2.8 on 2025-12-18 07:27

from django.db import migrations, models
import django.db.models.deletion


def link_contacts_to_companies(apps, schema_editor):
    """Link all contacts to their corresponding companies"""
    Contact = apps.get_model('dashboard', 'Contact')
    Company = apps.get_model('dashboard', 'Company')
    
    for contact in Contact.objects.all():
        if contact.company and not contact.new_company:
            # Find matching company
            try:
                company = Company.objects.get(company_name=contact.company)
                contact.new_company = company
                contact.save()
            except Company.DoesNotExist:
                # Create company if it doesn't exist
                company = Company.objects.create(
                    company_name=contact.company,
                    city_1=contact.location_city or 'Default City',
                    address_1=contact.individual_address or 'Default Address'
                )
                contact.new_company = company
                contact.save()


def reverse_link(apps, schema_editor):
    """Reverse the linking"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_add_company_relationship'),
    ]

    operations = [
        # Link contacts to companies
        migrations.RunPython(link_contacts_to_companies, reverse_link),
        
        # Remove old company field and rename new_company to company
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='new_company',
            new_name='company',
        ),
        
        # Make required fields non-nullable
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=200, verbose_name='Client/Contact Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_1',
            field=models.EmailField(max_length=254, verbose_name='Primary Email Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(max_length=20, verbose_name='Primary Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='individual_address',
            field=models.TextField(verbose_name='Individual Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company', verbose_name='Company'),
        ),
    ]
