# Generated by Django 5.2.8 on 2025-12-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_finalize_contact_company_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='inquiryhandler',
            name='company',
            field=models.ForeignKey(help_text='Select company from database', on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='dashboard.contact', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='inquiryhandler',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Auto-fetched based on company selection', max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text='Select company from database', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='dashboard.contact', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='dashboard.contact', verbose_name='Company'),
        ),
    ]
