# Generated by Django 5.2.8 on 2025-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_fix_legacy_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_1',
            field=models.CharField(max_length=100, unique=True, verbose_name='Primary City'),
        ),
    ]
