# Generated by Django 5.2.8 on 2025-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_add_city_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city_1',
            field=models.CharField(max_length=100, verbose_name='Primary City'),
        ),
    ]
