# Generated by Django 5.2.8 on 2025-12-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_city_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryhandler',
            name='next_date',
            field=models.DateField(blank=True, help_text='Enter next date manually (optional)', null=True, verbose_name='Next Date'),
        ),
        migrations.AddField(
            model_name='inquiryhandler',
            name='sales',
            field=models.ForeignKey(blank=True, help_text='Select sales person from database', limit_choices_to={'userprofile__roles__contains': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sales Person'),
        ),
        migrations.AlterField(
            model_name='inquiryhandler',
            name='ba',
            field=models.CharField(blank=True, help_text='Enter BA name manually', max_length=100, null=True, verbose_name='BA (Business Analyst)'),
        ),
    ]
