# Generated by Django 6.0 on 2025-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_enforce_date_of_quote_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryhandler',
            name='lead_description',
            field=models.TextField(blank=True, default='', help_text='Enter lead description manually', verbose_name='Lead Description'),
        ),
    ]
