# Generated by Django 6.0 on 2025-12-22 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_make_lead_description_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('revision', models.CharField(default='Rev A', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quotation_date', models.CharField(max_length=100)),
                ('to_person', models.CharField(max_length=200)),
                ('firm', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('payment_terms', models.TextField()),
                ('delivery_terms', models.TextField()),
                ('scope_description', models.CharField(max_length=300)),
                ('scope_line_1', models.CharField(max_length=300)),
                ('scope_line_2', models.CharField(max_length=300)),
                ('fixtures_data', models.JSONField(default=list)),
                ('fixtures_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
    ]
