# Generated by Django 5.2.9 on 2025-12-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Enter item name', max_length=200, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Enter quantity', max_digits=10, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter price per unit', max_digits=12, verbose_name='Price')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: Quantity × Price', max_digits=15, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['id'],
            },
        ),
    ]
