# Generated by Django 5.2.9 on 2025-12-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_code',
            field=models.CharField(blank=True, help_text='Item/Material code or SKU', max_length=100, null=True, verbose_name='Material Code'),
        ),
    ]
