# Generated by Django 5.2.9 on 2025-12-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_purchaseorderitem_material_code'),
    ]

    operations = [
    ]
