# Generated by Django 5.2.9 on 2025-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20251227_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Enter payment terms and conditions', null=True, verbose_name='Payment Terms'),
        ),
    ]
