# Generated by Django 5.2.9 on 2025-12-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_purchaseorder_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.PositiveIntegerField(blank=True, help_text='Enter payment terms in days (e.g., 45 for 45 days)', null=True, verbose_name='Payment Terms (Days)'),
        ),
    ]
