# Generated by Django 5.2.9 on 2025-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_purchaseorder_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50, verbose_name='PO Number'),
        ),
    ]
