# Generated by Django 5.2.9 on 2025-12-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated in format KEC/051/2526', max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
    ]
