# Generated by Django 5.2.9 on 2025-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_generate_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the invoice', max_length=20, verbose_name='Invoice Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Auto-calculated: GRN Date + Payment Terms from selected Purchase Order', null=True, verbose_name='Payment Due Date'),
        ),
    ]
