# Generated by Django 6.0 on 2025-12-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_add_status_to_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(help_text='Enter supply date manually', verbose_name='Supply Date')),
                ('description', models.TextField(help_text='Enter additional supply description', verbose_name='Additional Supply Description')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Enter quantity', max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Enter unit price', max_digits=12, verbose_name='Unit Price')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: Quantity × Unit Price', max_digits=15, verbose_name='Total Amount')),
                ('remarks', models.TextField(blank=True, help_text='Enter remarks (optional)', null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Select invoice from database', on_delete=django.db.models.deletion.CASCADE, related_name='additional_supplies', to='dashboard.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Additional Supply',
                'verbose_name_plural': 'Additional Supplies',
                'ordering': ['-created_at'],
            },
        ),
    ]
