# Generated by Django 6.0 on 2025-12-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_additionalsupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_index', models.IntegerField(help_text='Index of the fixture this image belongs to', verbose_name='Fixture Index')),
                ('image', models.ImageField(upload_to='draft_images/', verbose_name='Image File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.IntegerField(verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_images', to='dashboard.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Draft Image',
                'verbose_name_plural': 'Draft Images',
                'ordering': ['fixture_index'],
            },
        ),
    ]
