# Generated by Django 6.0 on 2025-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_draftimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the invoice', max_length=20, verbose_name='Invoice Status'),
        ),
    ]
